title:               Have a Good Life.
include:             ['_pages']
exclude:             ['_includes/notes_graph.json', '_notes/.obsidian/plugins/obsidian-daily-stats/data.json']
url:                "https://jethro.site"
timezone:           "America/Los_Angeles" # Set your timezone
# You may need to change the base URL depending on your deploy configuration.
# baseurl:             ''

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
use_html_extension:  false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: false

# Set to `true` to replace tweet URLs with Twitter embeds.
# Note that doing so will negatively the reader's privacy
# as their browser will communicate with Twitter's servers.
embed_tweets: true

permalink:           pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at
#  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  
sass:
  sass_dir:          _sass
  style:            :compressed

twitter_url: https://x.com/jethrojones
linkedin_url: https://linkedin.com/in/jethrojones
instagram_url: https://instagram.com/jethrojones
rss_url: https://jethro.site/feed_notes.xml

feed:
    path: feed_notes.xml
    
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block: false

collections:
  notes:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"

