name: Update Last Modified At

on: 
  push:
    branches:
      - main

jobs:
  update_last_modified:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3
      
    # Update last_modified_at field in markdown files
    - name: Update last_modified_at field
      run: |
        for file in $(git ls-files '*.md'); do
          if grep -q '^---' "$file"; then
            modified_date=$(date "+%Y-%m-%d %H:%M:%S")
            
            if grep -q 'last_modified_at:' "$file"; then
              sed -i "s/last_modified_at:.*/last_modified_at: $modified_date/" "$file"
            else
              sed -i "1,/^---$/ s/^---$/last_modified_at: $modified_date\n---/" "$file"
            fi
          fi
        done
        
    # Commit the changes
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add .
        git commit -m "Update last_modified_at fields"
        
    # Push the changes back to the repository
    - name: Push changes
      run: git push
