name: Update Last Modified At

on:
  push:
    branches:
      - main

jobs:
  update_last_modified:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.4'

      - name: Install Bundler
        run: gem install bundler

      - name: Install Dependencies
        run: bundle install

      - name: Update Last Modified At in Markdown Files
        run: |
          #!/bin/bash

          # Enable debugging mode to log all executed commands
          set -x

          # Loop through all markdown files being committed
          for file in $(git diff --cached --name-only --diff-filter=ACM | grep '.md$'); do
            echo "Processing file: $file"
            
            # Check if the file has front matter
            if grep -q '^---' "$file"; then
              # Get the current date
              modified_date=$(date "+%Y-%m-%d %H:%M:%S")
              echo "Modified date: $modified_date"
              
              # Define a flag to check if last_modified_at is found
              modified_at_found=false

              # Create a temporary file to store the updated content
              temp_file=$(mktemp) || { echo "Failed to create temp file"; exit 11; }

              # Read through the file line by line
              while IFS= read -r line; do
                # Check if the line contains 'last_modified_at' inside the front matter
                if [[ $line == last_modified_at* ]]; then
                  # Replace the last_modified_at value
                  echo "last_modified_at: $modified_date" >> "$temp_file"
                  modified_at_found=true
                else
                  # Copy the line to the temp file
                  echo "$line" >> "$temp_file"
                fi
              done < "$file"

              # If last_modified_at was not found, insert it after the first '---'
              if ! $modified_at_found; then
                # Insert after the first '---' in the front matter (Linux compatible sed command)
                sed -i "0,/^---$/!b;//a last_modified_at: $modified_date" "$temp_file" || { echo "sed command failed"; exit 11; }
              fi

              # Overwrite the original file with the modified file
              mv "$temp_file" "$file" || { echo "mv command failed"; exit 11; }

              # Stage the modified file for commit
              git add "$file" || { echo "git add failed"; exit 11; }
            fi
          done

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update last_modified_at fields" || echo "No changes to commit"
